trigger:
- feat/*

pool:
  vmImage: 'ubuntu-latest'  

jobs:
- job: setup_python_environment  
  steps:
  - script: |
      # Check out your code from the repository
      cd $(File_Path)
      python -m venv .venv
      .venv/bin/activate  
      pip install -r requirements.txt
    displayName: 'Set up Python environment'
- job: run_unit_test
  steps:
  -script: |
      test/python endpoint_test.py
